const CARD_CHANGE = "CARD_CHANGE";
const DATE_CHANGE = "DATE_CHANGE";
const CVV_CHANGE = "CVV_CHANGE";
const CARD_VALIDATION_CHANGE = "CARD_VALIDATION_CHANGE";
const DATE_VALIDATION_CHANGE = "DATE_VALIDATION_CHANGE";
const CVV_VALIDATION_CHANGE = "CVV_VALIDATION_CHANGE";
const SUBMIT_CARD = "SUBMIT_CARD";

export {
  CARD_CHANGE,
  DATE_CHANGE,
  CVV_CHANGE,
  CARD_VALIDATION_CHANGE,
  DATE_VALIDATION_CHANGE,
  CVV_VALIDATION_CHANGE,
  SUBMIT_CARD,
};
