name: Test and Deploy

on:
    push:
        branches:
            - main
    pull_request:
        branches: 
            - main

jobs:
    test-and-coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 21
            - run: npm ci
            - run: npm test
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  verbose: true

    publish-npm:
        needs: test-and-coverage
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 21
                  registry-url: https://registry.npmjs.org/
            - run: npm ci
            - run: npm run build
            - run: cp -R src/icons dist/
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}